### ISSUE TITLE
glClear, glClearColor equivalent not found

### ISSUE THREAD

**Issue by avagantamo** [TheBoneJarmer/TilarGL#2]
I'm not sure if I'm missing something, but the methods glClear and glClearColor dont seem to be available

**Comment by TheBoneJarmer** [comment]
Hi @avagantamo 

They are available in the GL10 class since they are part of OpenGL 1.0. So in order to use them, you need to call GL10.glClear and GL10.glClearColor.

With kind regards,
TheBoneJarmer
